#!/usr/bin/env bash
# This script deploys an RHACS Central CR into the specified namespace,
# obtains the admin password for the deployed Central instance, and then
# queries the scanner to scan the specified test image.
#
# Usage:
# roxctl-scan.sh <namespace> <test-image>
# 
# Example:
# roxctl-scan.sh my-test-ns quay.io/opdev/preflight:stable > output.json
# 
# Prerequisites:
# - OpenShift cluster in current oc/kubectl context, with permissions to
#   deploy in the specified namespace
# - RHACS operator deployed in the OpenShift cluster
# - Image pull secret for registry.redhat.io to be present in the `pull-secret` secret in `openshift-config` namespace
# - `roxctl` CLI present and executable in the PATH
# - `oc` CLI present and executable in the PATH
# - `jq` present and executable in the PATH
# - `curl` present and executable in the PATH

central_resource='{"apiVersion":"platform.stackrox.io/v1alpha1","kind":"Central","metadata":{"name":"stackrox-central-services"},"spec":{"configAsCode":{"configAsCodeComponent":"Enabled"},"monitoring":{"openshift":{"enabled":true}},"network":{"policies":"Enabled"},"central":{"notifierSecretsEncryption":{"enabled":false},"exposure":{"loadBalancer":{"enabled":false,"port":443},"nodePort":{"enabled":false},"route":{"enabled":true,"reencrypt":{"enabled":false}}},"telemetry":{"enabled":true},"db":{"isEnabled":"Default","connectionPoolSize":{"maxConnections":90,"minConnections":10},"persistence":{"persistentVolumeClaim":{"claimName":"central-db"}}},"persistence":{"persistentVolumeClaim":{"claimName":"stackrox-db"}}},"egress":{"connectivityPolicy":"Online"},"scannerV4":{"db":{"persistence":{"persistentVolumeClaim":{"claimName":"scanner-v4-db"}}},"indexer":{"scaling":{"autoScaling":"Enabled","maxReplicas":5,"minReplicas":1,"replicas":1}},"matcher":{"scaling":{"autoScaling":"Enabled","maxReplicas":5,"minReplicas":1,"replicas":1}}},"scanner":{"analyzer":{"scaling":{"autoScaling":"Enabled","maxReplicas":5,"minReplicas":1,"replicas":1}}}}}'
image_integration_template='{"name":"registry.redhat.io","type":"docker","categories":["REGISTRY"],"docker":{"endpoint":"registry.redhat.io","username":"","password":"","insecure":false},"autogenerated":false,"skipTestIntegration":false}'

run_scan() {
    { err=$(roxctl image scan --force --image "${image}" --insecure-skip-tls-verify --retries 0 --output json 2>&1 >&3 3>&-); } 3>&1
}

namespace="${1}"
image="${2}"
>&2 oc create namespace "${namespace}"
printf "%s" "${central_resource}" | >&2 oc apply -n "${namespace}" -f -

# Wait for Central instance to be ready
until >&2 oc wait --for=condition=ready pod -l app.kubernetes.io/component=central -n "${namespace}" --timeout 0; do
    sleep 5
done

# Check if the cluster pull secret (in openshift-config namespace) has an entry for registry.redhat.io and use it for
# configuring an image integration in RHACS for registry.redhat.io
registry_credentials="$(oc get secret/pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode }}' | jq -r '.auths."registry.redhat.io".auth')"
if [ "${registry_credentials}" = "null" ] || [ -z "${registry_credentials}" ]; then
    >&2 echo "Could not find registry credentials for registry.redhat.io. Please make sure the credentials are configured in the pull-secret secret."
    exit 1
fi

registry_username="$(printf "%s" "${registry_credentials}" | base64 -d | cut -d':' -f1)"
registry_password="$(printf "%s" "${registry_credentials}" | base64 -d | cut -d':' -f2)"
image_integration="$(printf "%s" "${image_integration_template}" | jq ".docker.username = \"${registry_username}\" | .docker.password = \"${registry_password}\"")"

# Get Central instance connection details
rox_host="$(oc get route -n "${namespace}" central -o json | jq -r .spec.host)"
ROX_ADMIN_PASSWORD="$(oc get secret -n "${namespace}" central-htpasswd -o json | jq -r .data.password | base64 -d)"
ROX_ENDPOINT="https://${rox_host}"
export ROX_ADMIN_PASSWORD ROX_ENDPOINT

# Create the image integration for registry.redhat.io via REST API
curl -ksS -o /dev/null -u "admin:${ROX_ADMIN_PASSWORD}" "${ROX_ENDPOINT}/v1/imageintegrations" --header "Content-Type: application/json" --data "${image_integration}"

# Wait for the Scanner V4 Matcher to be ready
matcher_status="$(curl -ksS -u "admin:${ROX_ADMIN_PASSWORD}" "${ROX_ENDPOINT}/v1/integrationhealth/vulndefinitions?component=SCANNER_V4" | jq -r .lastUpdatedTimestamp)"
while [ "${matcher_status}" = "null" ] || [ -z "${matcher_status}" ]; do
    >&2 echo "Scanner V4 is not ready yet, retrying soon..."
    sleep 60
    matcher_status="$(curl -ksS -u "admin:${ROX_ADMIN_PASSWORD}" "${ROX_ENDPOINT}/v1/integrationhealth/vulndefinitions?component=SCANNER_V4" | jq -r .lastUpdatedTimestamp)"
done

# Request image scan and wait for success
until run_scan; do
    >&2 echo "Scanner V4 encountered an error, retrying soon: ${err}"
    sleep 60
done

>&2 oc delete namespace "${namespace}"
